### ISSUE TITLE
create PrintView in code

### ISSUE THREAD

**Issue by skew** [johnkil/Print#15]
I have next code:
```java
        PrintView statusView = new PrintView(context);
```
and get this stack trace
```java
    java.lang.NullPointerException
            at com.github.johnkil.print.PrintDrawable.updateIconColors(PrintDrawable.java:241)
            at com.github.johnkil.print.PrintDrawable.<init>(PrintDrawable.java:148)
            at com.github.johnkil.print.PrintDrawable.<init>(PrintDrawable.java:41)
            at com.github.johnkil.print.PrintDrawable$Builder.build(PrintDrawable.java:117)
            at com.github.johnkil.print.PrintViewUtils.initIcon(PrintViewUtils.java:63)
            at com.github.johnkil.print.PrintView.init(PrintView.java:56)
            at com.github.johnkil.print.PrintView.<init>(PrintView.java:36)
            at su.keysoft.inventory.rfid_inventory.extendedrow.InventoryRow.<init>(InventoryRow.java:37)
```
in class **PrintViewUtils** method **initIcon** i have **AttributeSet attrs** is null.
And **PrintDrawable** have **mIconColor** is null.

Can you help me with this error? What i doing wrong.

**Comment by johnkil** [comment]
It's looks like a bug ( will fix it soon :wink:
