### ISSUE TITLE
RuntimeException: Font asset not found fonts/iconic-font.ttf

### ISSUE THREAD

**Issue by BenoitDuffez** [johnkil/Print#19]
I'm the developer of this project:
https://github.com/BenoitDuffez/AndroidCupsPrint

I received a [crash report](https://github.com/BenoitDuffez/AndroidCupsPrint/issues/29) from your code:
```
Fatal Exception: java.lang.RuntimeException: Unable to create application com.android.tools.fd.runtime.BootstrapApplication: java.lang.RuntimeException: Font asset not found fonts/iconic-font.ttf
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.RuntimeException: Font asset not found fonts/iconic-font.ttf
       at android.graphics.Typeface.createFromAsset(Typeface.java:190)
       at com.github.johnkil.print.TypefaceManager.load(TypefaceManager.java:48)
       at com.github.johnkil.print.PrintConfig.initDefault(PrintConfig.java:35)
       at io.github.benoitduffez.cupsprint.CupsPrintApp.onCreate(CupsPrintApp.java:45)
       at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

I thought you might be interested in knowing that.

**Comment by johnkil** [comment]
Font asset not found `fonts/iconic-font.ttf`. You are sure that you have `iconic-font.ttf` font in assets folder?

**Comment by BenoitDuffez** [comment]
I don't know unfortunately. I did not get that error. I'm the dev of another app, and one user of both my app and yours got this crash (generated by your app but caught by mine).

**Comment by BenoitDuffez** [comment]
Sorry I didn't see your project was a lib. So I guess that a developer X used your lib to create an app Y, and a user Z of Y wanted to print something (landing on my app) and it crashed because X didn't include the font.

So I guess you can close this issue and/or add a workaround in TypefaceManager.java:48.

**Comment by johnkil** [comment]
Yes you are right, someone has not added this font 😉
